# Generated by Django 4.2 on 2023-04-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Наименование заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Наименование организатора')),
            ],
            options={
                'verbose_name': 'Организатор',
                'verbose_name_plural': 'Организаторы',
            },
        ),
        migrations.AlterModelOptions(
            name='objecttype',
            options={'verbose_name': 'Тип объекта закупки', 'verbose_name_plural': 'Типы объекта закупки'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ('-start_date',), 'verbose_name': 'Тендер', 'verbose_name_plural': 'Тендеры'},
        ),
        migrations.AlterModelOptions(
            name='tendertype',
            options={'verbose_name': 'Тип закупки', 'verbose_name_plural': 'Типы закупки'},
        ),
        migrations.AlterField(
            model_name='tender',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='web_app.customer', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='web_app.organizer', verbose_name='Организатор'),
        ),
    ]
