# Generated by Django 4.2 on 2023-05-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenderitem',
            name='unique_tender_item',
        ),
    ]
