# Generated by Django 4.2 on 2023-04-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_customer_organizer_alter_objecttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код предмета по ОКПД')),
                ('title', models.TextField(db_index=True, verbose_name='Наименование предмета')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Стоимость')),
                ('tender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web_app.tender', verbose_name='Тендер предмета')),
            ],
            options={
                'verbose_name': 'Предмет закупки/контакта',
                'verbose_name_plural': 'Предметы закупки/контакта',
            },
        ),
    ]
